// UI/UX Design
const design = [
  {
    class: 'Tool',
    content: [
      {
        title: '灯果可视化',
        desc: '人工智能驱动的数据可视化BI软件',
        tag: 'Tool',
        url: 'http://bi.shenjian.io/landing/',
      },
      {
        title: 'SandDance',
        desc: 'Dynamic Visual Data Exploration',
        tag: 'Tool',
        url: 'https://www.sanddance.ms/',
      },
      {
        title: 'Generative.fm',
        desc: 'Ambient Generative Music by Alex Bainter',
        tag: 'Tool',
        url: 'https://generative.fm/',
      },
      {
        title: 'Fusion Design',
        desc: '协助企业设计师与前端构建并使用设计系统',
        tag: 'Tool',
        url: 'https://fusion.design/',
      },
      {
        title: 'Culrs',
        desc: 'a simple smart approach to choose color palettes',
        tag: 'Tool',
        url: 'https://culrs.com/#/',
      },
      {
        title: 'Ant Design',
        desc: '蚂蚁金服设计平台',
        tag: 'Tool',
        url: 'http://design.alipay.com/',
      },
      {
        title: 'Cleanmock',
        desc: 'Mockup your designs simply and beautifully.',
        tag: 'Tool',
        url: 'https://cleanmock.com/designer',
      },
      {
        title: '设计订阅',
        desc: '腾讯设计导航',
        tag: 'Tool',
        url: 'https://idesign.qq.com',
      },
      {
        title: 'Seeseed',
        desc: '无穷尽设计可能',
        tag: 'Tool',
        url: 'https://www.seeseed.com/',
      },
      {
        title: '图说设计模式',
        desc: 'Graphic Design Patterns',
        tag: 'Tool',
        url: 'https://design-patterns.readthedocs.io/zh_CN/latest/index.html',
      },
      {
        title: 'Animista',
        desc: 'a collection of CSS animations',
        tag: 'UI',
        url: 'https://animista.net/play/basic',
      },
      {
        title: 'unDraw',
        desc: 'Open-source illustrations for project',
        tag: 'Illustration',
        url: 'https://undraw.co/',
      },
      {
        title: 'Awesome Design Tools',
        desc: 'from wireframing and prototyping to animation, accessibility, AR, design systems and sound design.',
        tag: 'Tool',
        url: 'https://flawlessapp.io/designtools',
      },
      {
        title: 'ADVANCE DESIGN',
        desc: 'Dapollo设计开发工作台',
        tag: 'Tool',
        url: 'http://www.alipaydesign.com/tool',
      },
      {
        title: 'Lookin',
        desc: '免费好用的 iOS UI 调试软件',
        tag: 'Tool',
        url: 'https://lookin.work/',
      },
      {
        title: 'DesignCap',
        desc: 'Create Amazing Graphic Design for Free',
        tag: 'Tool',
        url: 'https://www.designcap.com/app/',
      },
      {
        title: 'IRA Design',
        desc: 'Build your own amazing illustrations @ Creative Tim',
        tag: 'Tool',
        url: 'https://iradesign.io/',
      },
    ],
  },
  {
    class: 'UI',
    content: [
      {
        title: 'UiforUS',
        desc: '让UI设计变得更简单',
        tag: 'Tool',
        url: 'https://www.uiforus.com/',
      },
      {
        title: 'Taro',
        desc: '遵循 React 语法规范的多端统一开发框架-凹凸实验室',
        tag: 'UI',
        url: 'https://taro.aotu.io/',
      },
      {
        title: 'Cleanmock',
        desc: 'Mockup your designs simply and beautifully.',
        tag: 'Tool',
        url: 'https://cleanmock.com/designer',
      },
      {
        title: 'MDUI',
        desc: 'Material Design User Interface',
        tag: 'UI',
        url: 'https://www.mdui.org/',
      },
      {
        title: 'Material Design for Bootstrap',
        desc: 'free UI KIT - Material Design for Bootstrap',
        tag: 'UI',
        url: 'https://mdbootstrap.com/',
      },
      {
        title: 'UI8',
        desc: 'UI Design Resources, UI Kits, Wireframes, Icons and More',
        tag: 'UI',
        url: 'https://ui8.net/',
      },
      {
        title: 'SUI Mobile',
        desc: '阿里巴巴国际UED前端出品移动端UI',
        tag: 'UI',
        url: 'http://m.sui.taobao.org/',
      },
      {
        title: 'Arction',
        desc: '快速、先进的 .NET图表控件 & LightningChart JS, WEB 图表库',
        tag: '',
        url: 'http://www.arction.cn/',
      },
      {
        title: 'Cruip',
        desc: 'HTML, React, and Vue.js landing page templates for startups',
        tag: '',
        url: 'https://cruip.com/',
      },
      {
        title: 'CSSFX',
        desc: 'Beautifully simple click-to-copy CSS effects',
        tag: '',
        url: 'https://cssfx.dev/',
      },
    ],
  },
  {
    class: 'Resource',
    content: [
      {
        title: 'Ouch.pics',
        desc: 'Free vector illustrations',
        tag: 'Tool',
        url: 'https://icons8.com/ouch',
      },
      {
        title: 'Pngtree',
        desc: 'Millions of PNG Images, Backgrounds and Vectors for Free Download',
        tag: 'Tool',
        url: 'https://pngtree.com/',
      },
      {
        title: 'DrawKit',
        desc: 'Beautiful free illustrations',
        tag: 'Tool',
        url: 'https://www.drawkit.io/',
      },
      {
        title: 'Humaaans',
        desc: 'Mix-&-Match illustration library',
        tag: 'Tool',
        url: 'https://www.humaaans.com/',
      },
      {
        title: 'ManyPixels',
        desc: 'Illustration Gallery by ManyPixels | Open-Source Editable Illustrations',
        tag: 'Tool',
        url: 'https://www.manypixels.co/gallery/',
      },
      {
        title: 'Free SVG Images',
        desc: 'Free Illustrations [Free SVG Images] MIT licensed Vectors',
        tag: 'Tool',
        url: 'https://lukaszadam.com/illustrations',
      },
      {
        title: 'Pixabay',
        desc: '1 million+ Stunning Free Images to Use Anywhere',
        tag: 'Tool',
        url: 'https://pixabay.com/',
      },
      {
        title: 'Collect UI',
        desc: 'Daily inspiration collected',
        tag: 'Tool',
        url: 'http://collectui.com/',
      },
    ],
  },
  {
    class: 'Color',
    content: [
      {
        title: 'CSS渐变',
        desc: 'CSS渐变',
        tag: 'Tool',
        url: 'https://www.bestvist.com/css-gradient',
      },
      {
        title: 'Colorgg',
        desc: 'Colorgg颜色大全,颜色搭配,颜色代码表查询',
        tag: 'Tool',
        url: 'https://www.colorgg.com/',
      },
      {
        title: 'Trianglify',
        desc: 'Low Poly Pattern Generator',
        tag: 'Tool',
        url: 'https://trianglify.io/',
      },
      {
        title: 'WebGradients',
        desc: 'Fresh Background Gradients',
        tag: 'Tool',
        url: 'https://webgradients.com/',
      },
      {
        title: 'CoolHue',
        desc: 'Coolest Gradient Hues and Swatches',
        tag: 'Tool',
        url: 'https://webkul.github.io/coolhue/',
      },
      {
        title: 'HSL Color Picker',
        desc: 'CREATED FOR YOUR ENJOYMENT',
        tag: 'Tool',
        url: 'http://hslpicker.com/',
      },
    ],
  },
  {
    class: 'Font',
    content: [
      {
        title: '方正字库',
        desc: '免费字体_PS字体_方正字体',
        tag: 'Source',
        url: 'http://www.foundertype.com/',
      },
      {
        title: '造字工房',
        desc: '造字工房',
        tag: 'Source',
        url: 'http://www.makefont.com/',
      },
      {
        title: '汉仪字库',
        desc: '用心绽放文字之美',
        tag: 'Source',
        url: 'http://www.hanyi.com.cn/',
      },
      {
        title: '华康字型',
        desc: '华康字型',
        tag: 'Source',
        url: 'https://www.dynacw.com.cn/',
      },
      {
        title: '文悦字库',
        desc: 'Timeline',
        tag: 'Source',
        url: 'https://wytype.com/',
      },
      {
        title: 'Google Fonts',
        desc: 'Google Fonts',
        tag: 'Source',
        url: 'https://fonts.google.com/',
      },
      {
        title: '思源宋体',
        desc: '思源宋体',
        tag: 'Source',
        url: 'https://source.typekit.com',
      },
      {
        title: '字由',
        desc: '设计师必备字体利器',
        tag: 'Tool',
        url: 'http://www.hellofont.cn/',
      },
      {
        title: 'Adobe Fonts',
        desc: 'Explore unlimited fonts',
        tag: 'Source',
        url: 'https://fonts.adobe.com/',
      },
      {
        title: 'Font Squirrel',
        desc: 'Free Fonts! Legit Free & Quality',
        tag: 'Source',
        url: 'https://www.fontsquirrel.com/',
      },
      {
        title: 'Font Library',
        desc: 'Font Library',
        tag: 'Source',
        url: 'https://fontlibrary.org/',
      },
    ],
  },
  {
    class: 'Icon',
    content: [
      {
        title: '草莓图标库',
        desc: 'A Free and Open Source Iconic Font Library for Developers',
        tag: 'Tool',
        url: 'http://chuangzaoshi.com/icon/',
      },
      {
        title: 'Iconfont',
        desc: '阿里巴巴矢量图标库',
        tag: 'Tool',
        url: 'https://www.iconfont.cn/',
      },
      {
        title: 'IcoMoon',
        desc: 'Icon Font & SVG Icon Sets',
        tag: 'Tool',
        url: 'https://icomoon.io/',
      },
      {
        title: 'Remix Icon',
        desc: 'Open source icon library',
        tag: 'Tool',
        url: 'https://remixicon.com/',
      },
      {
        title: 'Zwicon',
        desc: 'Icon Set',
        tag: 'Tool',
        url: 'https://www.zwicon.com/cheatsheet.html',
      },
      {
        title: 'Emojipedia',
        desc: 'Home of Emoji Meanings 💁👌🎍😍',
        tag: 'Tool',
        url: 'https://emojipedia.org/',
      },
      {
        title: 'Pichon',
        desc: '86,000 Icons in a Free App',
        tag: 'Tool',
        url: 'https://icons8.com/app',
      },
    ],
  },
]

export default design
