// Programming development
const develop = [
  {
    class: 'Statistics',
    content: [
      {
        title: 'Hacker News',
        desc: 'News',
        tag: 'Tool',
        url: 'https://news.ycombinator.com/',
      },
      {
        title: '机器之心',
        desc: '全球人工智能信息服务',
        tag: 'Source',
        url: 'https://www.jiqizhixin.com/',
      },
      {
        title: 'GitHub Trending',
        desc: 'Trending repositories on GitHub today',
        tag: 'Tool',
        url: 'https://github.com/trending',
      },
      {
        title: 'StaticGen',
        desc: 'Top Open Source Static Site Generators',
        tag: 'Tool',
        url: 'https://www.staticgen.com/',
      },
      {
        title: '独角兽排行榜',
        desc: '2019 年独角兽企业排名',
        tag: 'Tool',
        url: 'https://dujiaoshou.io/',
      },
      {
        title: '亚马跌',
        desc: '一个选购参考网站',
        tag: 'Tool',
        url: 'https://www.ymdie.com/',
      },
      {
        title: 'HelloGitHub',
        desc: '分享 GitHub 入门级、有趣的开源项目',
        tag: 'Tool',
        url: 'https://hellogithub.com/',
      },
      {
        title: '独立',
        desc: '中国独立 iOS 和 macOS 开发者项目列表',
        tag: 'Tool',
        url: 'https://josephchang10.github.io/chinese-indie-hackers/',
      },
      {
        title: 'Hunter',
        desc: 'Find the websites using certain technologies',
        tag: 'Tool',
        url: 'https://techlookup.hunter.io/',
      },
      {
        title: 'GitHuber',
        desc: 'Github 开发者社区',
        tag: 'Tool',
        url: 'https://githuber.cn/',
      },
      {
        title: 'USLD',
        desc: 'User Shares of Linux Distros',
        tag: 'Tool',
        url: 'http://7z.cx/dsc/',
      },
      {
        title: 'The Google Cemetery',
        desc: 'Dead Google products',
        tag: 'Tool',
        url: 'https://gcemetery.co/',
      },
    ],
  },
  {
    class: 'Community',
    content: [
      {
        title: '掘金',
        desc: '一个帮助开发者成长的社区',
        tag: 'Tool',
        url: 'https://juejin.im/',
      },
      {
        title: 'V2EX',
        desc: 'Way To Explore',
        tag: 'Tool',
        url: 'https://v2ex.com/',
      },
      {
        title: 'CNode',
        desc: 'Node.js专业中文社区',
        tag: 'Tool',
        url: 'https://cnodejs.org/',
      },
      {
        title: 'Stack Overflow',
        desc: 'Where Developers Learn, Share, & Build Careers',
        tag: 'Tool',
        url: 'https://stackoverflow.com/',
      },
      {
        title: 'LaTeX工作室',
        desc: '分享与学习LaTeX的王国',
        tag: 'Tool',
        url: 'http://www.latexstudio.net/',
      },
      {
        title: 'Product Hunt',
        desc: 'The best new products in tech',
        tag: 'Tool',
        url: 'https://www.producthunt.com/',
      },
      {
        title: '新趣集',
        desc: '一起发现有趣的新产品',
        tag: 'Tool',
        url: 'https://xinquji.com/',
      },
      {
        title: '小专栏',
        desc: '专业人士的创作知识社区',
        tag: 'Tool',
        url: 'https://xiaozhuanlan.com/',
      },
      {
        title: 'Gitter',
        desc: '开发者交谈的地方',
        tag: 'Tool',
        url: 'https://gitter.im/',
      },
    ],
  },
  {
    class: 'Resource',
    content: [
      {
        title: 'GitSheet',
        desc: 'A dead simple git cheatsheet.',
        tag: 'Tool',
        url: 'https://gitsheet.wtf/',
      },
      {
        title: 'Flex.io',
        desc: 'On-demand data from web services, directly in your spreadsheet.',
        tag: 'Tool',
        url: 'https://www.flex.io/',
      },
      {
        title: '码灵程序员导航',
        desc: '一个帮助开发者成长的程序员网址导航',
        tag: 'Tool',
        url: 'https://nav.imaring.com/',
      },
      {
        title: '代码片段',
        desc: '代码片段',
        tag: 'Tool',
        url: 'http://www.codesnippet.cn/',
      },
      {
        title: '片段',
        desc: '代码片段',
        tag: 'Tool',
        url: 'https://pianduan.fun/',
      },
      {
        title: 'searchcode',
        desc: 'source code search engine',
        tag: 'Tool',
        url: 'https://searchcode.com/',
      },
      {
        title: '程序命令搜索',
        desc: '程序命令搜索',
        tag: 'Tool',
        url: 'http://cmd.alibt.top/',
      },
      {
        title: 'VisuAlgo',
        desc: '数据结构和算法动态可视化',
        tag: 'Tool',
        url: 'https://visualgo.net/zh',
      },
      {
        title: '接口大全',
        desc: '免费API，收集所有免费的API',
        tag: 'Tool',
        url: 'https://www.free-api.com/',
      },
      {
        title: 'Twilio',
        desc: 'Communication APIs for SMS, Voice, Video and Authentication',
        tag: 'Tool',
        url: 'https://www.twilio.com/',
      },
      {
        title: 'Linux网站导航',
        desc: '做个有用的导航',
        tag: 'Tool',
        url: 'http://linux.ubuntu.org.cn/',
      },
      {
        title: 'mlhub',
        desc: '机器学习导航站',
        tag: 'Tool',
        url: 'https://www.mlhub123.com/',
      },
      {
        title: 'Scrumpy',
        desc: 'A Beautiful Project Management Tool for Agile Teams',
        tag: 'Tool',
        url: 'https://scrumpy.io/',
      },
      {
        title: '前端导航',
        desc: '',
        tag: 'Tool',
        url: 'https://javasoho.com/',
      },
      {
        title: 'React-UWP',
        desc: 'React-UWP App Developer | Docs',
        tag: 'Tool',
        url: 'https://www.react-uwp.com/',
      },
      {
        title: 'Easy Mock',
        desc: '更简单高效的伪造数据',
        tag: 'Tool',
        url: 'https://easy-mock.com',
      },
      {
        title: 'WooYun知识库',
        desc: '',
        tag: 'Tool',
        url: 'https://wooyun.kieran.top',
      },
      {
        title: 'Unicode字符百科',
        desc: '',
        tag: 'Tool',
        url: 'https://unicode-table.com',
      },
      {
        title: 'Python Extension',
        desc: 'Unofficial Windows Binaries for Python Extension Packages',
        tag: 'Tool',
        url: 'https://www.lfd.uci.edu/~gohlke/pythonlibs/',
      },
      {
        title: 'CSS Reference',
        desc: 'A free visual guide to CSS',
        tag: 'Tool',
        url: 'https://cssreference.io/',
      },
      {
        title: 'HTML Reference',
        desc: 'A free guide to all HTML elements and attributes',
        tag: 'Tool',
        url: 'https://htmlreference.io/',
      },
      {
        title: 'explainshell',
        desc: 'match command-line arguments to their help text',
        tag: 'Tool',
        url: 'https://explainshell.com/',
      },
      {
        title: 'Draw.io',
        desc: 'Online diagramming application  and flowchart maker',
        tag: 'Tool',
        url: 'https://www.draw.io/',
      },
      {
        title: 'Mergely',
        desc: 'Diff text documents online',
        tag: 'Tool',
        url: 'http://www.mergely.com/',
      },
      {
        title: 'Cacher',
        desc: 'Code snippet organizer for pros',
        tag: 'Tool',
        url: 'https://www.cacher.io/',
      },
      {
        title: 'Beyondcow',
        desc: '',
        tag: 'Tool',
        url: 'https://www.beyondcow.com/',
      },
      {
        title: 'Animista',
        desc: 'CSS Animations',
        tag: 'Tool',
        url: 'http://animista.net/',
      },
      {
        title: 'Libraries',
        desc: 'The Open Source Discovery Service',
        tag: 'Tool',
        url: 'https://libraries.io/',
      },
      {
        title: 'Linux Kernel',
        desc: 'The Linux Kernel Archives',
        tag: 'Tool',
        url: 'https://www.kernel.org/',
      },
      {
        title: 'CSS Humor',
        desc: 'CSS Humor » Fun with CSS!',
        tag: 'Tool',
        url: 'https://csshumor.com/',
      },
      {
        title: 'cssdb',
        desc: 'What’s next for CSS?',
        tag: 'Tool',
        url: 'https://cssdb.org/',
      },
    ],
  },
  {
    class: 'Tool',
    content: [
      {
        title: 'Can I use.',
        desc: 'Can I use... Support tables for HTML5, CSS3, etc',
        tag: 'Tool',
        url: 'https://www.caniuse.com/',
      },
      {
        title: 'I18n Translation',
        desc: 'I18n Translation Search Engine',
        tag: 'Tool',
        url: 'https://i18ns.com',
      },
      {
        title: 'LiveReload',
        desc: "Land where browsers don't need a Refresh button",
        tag: 'Tool',
        url: 'http://livereload.com/',
      },
      {
        title: 'Codeshare',
        desc: 'Share code in real-time with developers in your browser',
        tag: 'Tool',
        url: 'https://codeshare.io/',
      },
      {
        title: 'Git History',
        desc: 'Quickly browse the history of files in any git repo',
        tag: 'Tool',
        url: 'https://github.githistory.xyz/',
      },
      {
        title: 'Create App',
        desc: 'start a new webpack or Parcel project',
        tag: 'Tool',
        url: 'https://createapp.dev/',
      },
      {
        title: 'Github Contributions',
        desc: 'GitHub Contributions Chart Generator',
        tag: 'Tool',
        url: 'https://github-contributions.now.sh/',
      },
      {
        title: 'ngrok 内网穿透',
        desc: 'secure introspectable tunnels to localhost',
        tag: 'Tool',
        url: 'https://ngrok.com/',
      },
      {
        title: 'JavaScript Visualizer',
        desc: 'Visualizing Execution Context, Hoisting, Closures, and Scopes in JavaScript.',
        tag: 'Tool',
        url: 'https://tylermcginnis.com/javascript-visualizer/',
      },
      {
        title: 'Regexper',
        desc: 'Regular expression visualizer using railroad diagrams',
        tag: 'Tool',
        url: 'https://regexper.com/',
      },
      {
        title: 'regex101',
        desc: 'Online regex tester and debugger',
        tag: 'Tool',
        url: 'https://regex101.com/',
      },
      {
        title: 'UnCSS Online',
        desc: 'Simply UnCSS your styles online!',
        tag: 'Tool',
        url: 'https://uncss-online.com/',
      },
      {
        title: 'Clippy',
        desc: 'CSS clip-path maker',
        tag: 'Tool',
        url: 'https://bennettfeely.com/clippy/',
      },
      {
        title: 'Twilio',
        desc: 'Communication APIs for SMS, Voice, Video and Authentication',
        tag: 'Tool',
        url: 'https://www.twilio.com/',
      },
      {
        title: 'Syncd',
        desc: '自动化部署工具',
        tag: 'Tool',
        url: 'https://syncd.cc/',
      },
      {
        title: 'lera.ai',
        desc: 'Visualize and track learning',
        tag: 'Tool',
        url: 'https://lera.ai/',
      },
      {
        title: 'Codeimg.io',
        desc: 'Create and share beautiful images of your source code.',
        tag: 'Tool',
        url: 'https://codeimg.io/',
      },
      {
        title: 'Scrumpy',
        desc: 'A Beautiful Project Management Tool for Agile Teams',
        tag: 'Tool',
        url: 'https://scrumpy.io/',
      },
      {
        title: 'web.dev',
        desc: "Get the web's modern capabilities on your own sites and apps",
        tag: 'Tool',
        url: 'https://web.dev/',
      },
      {
        title: 'React-UWP',
        desc: 'React-UWP App Developer | Docs',
        tag: 'Tool',
        url: 'https://www.react-uwp.com/',
      },
      {
        title: 'Easy Mock',
        desc: '更简单高效的伪造数据',
        tag: 'Tool',
        url: 'https://easy-mock.com',
      },
      {
        title: 'Python Extension',
        desc: 'Unofficial Windows Binaries for Python Extension Packages',
        tag: 'Tool',
        url: 'https://www.lfd.uci.edu/~gohlke/pythonlibs/',
      },
      {
        title: 'CSS Reference',
        desc: 'A free visual guide to CSS',
        tag: 'Tool',
        url: 'https://cssreference.io/',
      },
      {
        title: 'HTML Reference',
        desc: 'A free guide to all HTML elements and attributes',
        tag: 'Tool',
        url: 'https://htmlreference.io/',
      },
      {
        title: 'explainshell',
        desc: 'match command-line arguments to their help text',
        tag: 'Tool',
        url: 'https://explainshell.com/',
      },
      {
        title: 'Draw.io',
        desc: 'Online diagramming application and flowchart maker',
        tag: 'Tool',
        url: 'https://www.draw.io/',
      },
      {
        title: 'Mergely',
        desc: 'Diff text documents online',
        tag: 'Tool',
        url: 'http://www.mergely.com/',
      },
      {
        title: 'TablePlus',
        desc: 'Modern, Native Tool for Database Management',
        tag: 'Tool',
        url: 'https://tableplus.io/',
      },
      {
        title: 'DevDocs API',
        desc: '',
        tag: 'Tool',
        url: 'http://devdocs.io/',
      },
      {
        title: 'Dash',
        desc: 'API Documentation Browser, Snippet Manager - Kapeli',
        tag: 'Tool',
        url: 'https://kapeli.com',
      },
      {
        title: 'Zeal',
        desc: 'Offline Documentation Browser',
        tag: 'Tool',
        url: 'https://zealdocs.org/',
      },
      {
        title: 'Carbon',
        desc: '',
        tag: 'Tool',
        url: 'https://carbon.now.sh',
      },
      {
        title: 'CodePen',
        desc: 'Create a New Pen',
        tag: 'Tool',
        url: 'https://codepen.io',
      },
      {
        title: 'CoderPad',
        desc: 'Help you hire better candidates faster',
        tag: 'Tool',
        url: 'https://coderpad.io/',
      },
      {
        title: 'Cacher',
        desc: 'Code snippet organizer for pros',
        tag: 'Tool',
        url: 'https://www.cacher.io/',
      },
      {
        title: 'Beyondcow',
        desc: '',
        tag: 'Tool',
        url: 'https://www.beyondcow.com/',
      },
      {
        title: 'Animista',
        desc: 'CSS Animations',
        tag: 'Tool',
        url: 'http://animista.net/',
      },
      {
        title: 'Tables Generator',
        desc: 'Create LaTeX tables online',
        tag: 'Tool',
        url: 'https://www.tablesgenerator.com/',
      },
      {
        title: 'Console Compiler',
        desc: 'Console Compiler',
        tag: 'Tool',
        url: 'https://compiler.run/',
      },
      {
        title: 'ASCIIFlow Infinity',
        desc: 'Infinite ASCII diagrams',
        tag: 'Tool',
        url: 'http://asciiflow.com/',
      },
      {
        title: 'asciinema',
        desc: 'Record and share your terminal sessions, the right way',
        tag: 'Tool',
        url: 'https://asciinema.org/',
      },
    ],
  },
  {
    class: 'Project',
    content: [
      {
        title: '众成翻译',
        desc: '翻译，从此起步',
        tag: 'Tool',
        url: 'https://www.zcfy.cc/',
      },
      {
        title: '掘金翻译计划',
        desc: '一个翻译优质互联网技术文章的社区',
        tag: 'Tool',
        url: 'https://github.com/xitu/gold-miner',
      },
      {
        title: '译言古登堡计划',
        desc: '',
        tag: 'Tool',
        url: 'http://g.yeeyan.org/',
      },
      {
        title: 'OpenWrt Project',
        desc: 'Welcome to the OpenWrt Project',
        tag: 'Tool',
        url: 'https://openwrt.org/',
      },
    ],
  },
  {
    class: 'Coding',
    content: [
      {
        title: 'SPOJ',
        desc: 'Sphere Online Judge',
        tag: 'Tool',
        url: 'https://www.spoj.com/',
      },
      {
        title: 'hihoCoder',
        desc: '用高水平的程序设计比赛提升编程水平',
        tag: 'Tool',
        url: 'http://www.hihocoder.com/',
      },
      {
        title: 'LeetCode',
        desc: 'Online Programming Learning Platform',
        tag: 'Tool',
        url: 'https://leetcode.com/',
      },
      {
        title: 'LintCode',
        desc: '编程面试题在线训练平台',
        tag: 'Tool',
        url: 'https://www.lintcode.com',
      },
      {
        title: '牛客网',
        desc: '专业 IT 笔试面试备考平台，求职题库',
        tag: 'Tool',
        url: 'https://www.nowcoder.com/',
      },
      {
        title: 'SoloLearn',
        desc: 'Learn to Code for Free',
        tag: 'Tool',
        url: 'https://www.sololearn.com/',
      },
    ],
  },
  {
    class: 'CDN',
    content: [
      {
        title: 'UNPKG',
        desc: 'The CDN for everything on npm',
        tag: 'Tool',
        url: 'https://unpkg.com',
      },
      {
        title: 'RawGit',
        desc: '',
        tag: 'Tool',
        url: 'https://rawgit.com/',
      },
      {
        title: 'jsDelivr',
        desc: 'Open Source CDN for npm & GitHub',
        tag: 'Tool',
        url: 'https://www.jsdelivr.com',
      },
    ],
  },
]

export default develop
